class_name ChapterData
extends Resource


@export var title: String

@export var battle_scene_path: String # (String, FILE, "*.tscn")

@export var script_background: Texture2D
@export var dialogue_background: Texture2D
@export var post_battle_script_background: Texture2D

@export var script_audio_stream: AudioStream
@export var dialogue_audio_stream: AudioStream
@export var post_battle_script_audio_stream: AudioStream

# Battle information. Autogenerated by plugin and overwritten at build time.
# Do not edit manually.
@export var battle_info: Resource
