extends DialogueCutscene


@export var pair: String = "YACHIE_AND_SAKI"
@export var support_level: int = 1 # (int, 1, 4)


func on_instance(data: Object) -> void:
	assert(data is SupportDialogueData)
	
	pair = data.pair
	support_level = data.support_level


func get_dialogue_json_filename() -> String:
	return "res://text/autogenerated/support_level_%d_%s.json" % [support_level, pair.to_lower()]


func _skip_dialogue() -> void:
	if not is_dialogue_skipped:
		is_dialogue_skipped = true
		
		if Loader.change_scene_to_file("res://ui/pre_battle_menu/stack_based_pre_battle_menu.tscn") != OK:
			printerr("Failed to change scene")

		set_process(false)


func _set_parameters_from_chapter_data() -> void:
	printerr("TODO: Implement _set_parameters_from_chapter_data() in SupportSelectionMenu")
