#!/usr/bin/env python3
"""Build the SIGNAL / 108 — Off-Network re-skin mapping workbook.

Modern Water Margin x The World Ends With You re-skin: a drowned near-future
megacity (NEO-LIANG) run by a civic super-app (HARMONY); the wrongfully dead
wake Off-Network, names scrubbed, and are conscripted into a hidden Game where
you pair up or are deleted. 108 of the erased gather in the Margins and learn
their deaths were scheduled in the Index before they ever died.

Tabs: Overview, Storyline, Chapter Names, Narration, Characters, Enemies, Banter.
Each shows original (Terra Battle) text beside the re-skin text. No formulas.
This is a TEXT + NAME + ART overlay only. No stage or battle layout data changes.
"""
import json
import os
import re
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "Outer_Heaven_Reskin.xlsx")
data = json.load(open(os.path.join(ROOT, "tools", "out", "terra_dataset.json")))


def slug(n):
    return re.sub(r"[^a-z0-9]+", "_", n.lower()).strip("_")


chapters = {c["num"]: (c["name"], slug(c["name"])) for c in data["chapters"]}


def orig_narr(s):
    p = os.path.join(ROOT, "text", "autogenerated", f"script_{s}.json")
    if not os.path.exists(p):
        return ""
    return "\n\n".join(x.get("line", "") for x in json.load(open(p)))


def orig_banter(s):
    p = os.path.join(ROOT, "text", "autogenerated", f"dialogue_{s}.json")
    if not os.path.exists(p):
        return []
    return [(x.get("speaker", ""), x.get("line", "")) for x in json.load(open(p))]


# Bespoke boss names + appearance, keyed by exact original name.
# Officers and machines for the Commission, beasts as beasts, council guardians late.
BOSS = {
    "1AOO": ("Council Warden Alpha", "A tower-tall guardian machine unfolded from the Commission's bones, blade etched with the names of prior cycles."),
    "2BOO": ("Council Warden Beta", "Twin to the first, a walking wall whose pike clears a lane a dozen souls wide."),
    "3COO": ("Council Warden Gamma", "The third tower guardian, a vast rail-archer raining cold bolts of policy."),
    "6ZOO": ("the First Warden", "The oldest guardian machine, blade wide as a service gate, built when the jars were young."),
    "54B2": ("Defector Frame 54", "A war frame that slipped its handlers, half rust, half grudge."),
    "???": ("the Unwritten", "A Southbank blade with no file, no flag, and no fear. The system reads nothing at all."),
    "Ancient Key": ("the Vault Key", "A floating relic shaped like a vast key, warden of the door the tower pretends is not there."),
    "Ancient Sadness": ("Old Grief", "A mountain of sorrow given shape, weeping for wards it could not save."),
    "Antlion": ("the Sinkhole Beast", "A burrowing horror whose jaws turn the field into a funnel of falling ground."),
    "Apirath": ("Apirath, the Toll-Keeper", "A towering bridge spirit robed in living stormcloud, collecting what crossings cost."),
    "Arachnobot": ("the Loom Machine", "An iron spider strung with cable and wire, weaving walls out of what it catches."),
    "Ba'gunar": ("the Jade Unicorn, Cornered", "Lu Junyi with nothing left to lose and excellent fencing lessons, fighting like a man mid-question."),
    "Beastfolk Hero": ("the Beast-Clan Champion", "The proudest fighter of the horned clans, blade raised against city and crew alike."),
    "Burnbot Redux": ("the Furnace Engine, Relit", "A rebuilt furnace machine, hotter and crueler than its first fire, venting blue flame."),
    "Celestial Dragon": ("the Leashed Sky-Drake", "A serpent of cloud and gold, collared by the tower and loosed on Deviants."),
    "Cerberus": ("the Three-Headed Watchdog", "A fire-maned hound of three heads chained to the gate of the deep."),
    "Craggy Leviathan": ("the Quarry Leviathan", "A district-shouldered beast of crag and rebar, risen from the buried foundations."),
    "Cybergolem": ("the First Works Machine", "An early city machine of riveted iron, the Commission's crudest hand."),
    "Cyberwyrm": ("the Cable Wyrm", "A young mechanical wyrm sheathed in braided cable and plate."),
    "Dark Dragon": ("the Night Dragon", "A drake of living dark, its breath a hole cut clean in the air."),
    "EM Generator": ("the Core Generator", "The humming heart of the under-grid, a machine that drinks current and life alike."),
    "Energos": ("the Gravity Engine", "A void-cored colossus that bends weight and light around its hunger."),
    "Energy Aspirator": ("the Siphon Machine", "A bladed machine that drains the strength from the living to feed the tower."),
    "Enerzerk": ("the Overcharged Sentinel", "A crackling rail-archer overcharged past every safety, each bolt a thunderclap."),
    "Flame Urchin": ("the Ember Urchin", "A spiked sphere of live coal, every quill a lance of fire."),
    "Fortified Oxsecian Bulwark": ("the Enforcement Bulwark", "A fortress machine of the war corps, walls for skin, storms for arrows."),
    "Giant Nega": ("the Greater Hollow", "A vast walking absence, a beast made of everything the city erased."),
    "Gigaworm": ("the Tunnel Worm", "A district-long worm that swallows the ground it crosses."),
    "Golem": ("the Concrete Sentinel", "A hulking guardian of poured concrete, slow, patient, unstoppable."),
    "Ice Golem": ("the Ice Sentinel", "A golem cut from black lake ice, breathing a cold that stops the heart."),
    "Ice Urchin": ("the Frost Urchin", "A spiked sphere of black ice, quills of killing frost."),
    "Jade Guardian": ("the Jade Warden", "A serene guardian statue in green and frost, beautiful and merciless."),
    "Jag": ("Jag, the Cinder Runner", "A lean fire-runner cast out of the enforcement corps, jacket smoldering at the hem."),
    "Kraken": ("the Under-Lake Kraken", "A many-armed horror of the drowned canals, dragging hulls and swimmers down together."),
    "Layla": ("Layla, the Frost Officer", "A regal Commission officer of the cold floors, a winter given a badge."),
    "Lich": ("the Bone Clerk", "A withered dead bureaucrat still stamping warrants in the buried archive."),
    "Lizardfolk Hero": ("the Serpent-Folk Champion", "The river clans' chosen blade, cold-eyed and unbeaten until now."),
    "Lizardfolk Warrior": ("the Serpent-Folk Warlord", "A towering river-clan champion swollen with stolen strength."),
    "Lock-On+": ("the Targeting Array", "A multi-eyed machine that paints every foe for its lances."),
    "Lock-On 333+": ("the Greater Targeting Array", "An upgraded targeting machine, three hundred eyes and no mercy."),
    "Magic Amp": ("the Curse Node", "A floating node that doubles the harm of everything around it; break it first."),
    "Power Amp": ("the War Node", "A floating node that doubles the strength of everything around it; break it first."),
    "Mantle Mammoth": ("the Magma Mammoth", "A tusked colossus of molten foundation-rock, each step a small eruption."),
    "Mantledrake": ("the Magma Drake", "A lava-veined drake newly woken from the burning deep."),
    "Marilith": ("the Six-Armed Serpent", "A six-armed serpent spirit with a blade in every hand."),
    "Mechabird": ("the Iron Hawk", "A mechanical bird of prey, talons of cold iron, patient as a warrant."),
    "Mechadrake": ("the Iron Drake", "A clockwork dragon strung with live current, scales of riveted plate."),
    "Mechadrake Redux": ("the Iron Drake, Rebuilt", "The same dragon rebuilt darker and deadlier, breathing shadow instead of sparks."),
    "Megacell": ("the Splitting Mass", "A swollen cold mass that splits and reforms, hard to put down for good."),
    "Mothbot Queen": ("the Drone-Moth Queen", "A great machine moth that spawns lesser drones, scattering iron dust."),
    "Negabeast": ("the Hollow Beast", "A beast made of absence, eating color and sound as it comes."),
    "Onyx Dragon": ("the Onyx Dragon", "A full-grown drake of black crystal, ancient and proud."),
    "Young Onyx Dragon": ("the Onyx Dragon, Fledgling", "The same drake half-grown, black scales not yet hardened, no less deadly."),
    "Orbling": ("Removal Foreman Tu", "The removal squad's foreman, a swollen patrol orb wearing its work order like a crown."),
    "Oxsecian Airgrunt": ("Enforcement Skirmisher, Elite", "An elite flying war frame of the enforcement corps."),
    "Oxsecian Bomber": ("Enforcement Bombardier", "A war frame laden with shaped charges."),
    "Oxsecian Bomber EX": ("Enforcement Bombardier, Mk II", "An upgraded bombardier frame, twice the charges, twice the ruin."),
    "Oxsecian Fighter EX": ("Enforcement Vanguard, Mk II", "A peak war frame, the corps' front line made monstrous."),
    "Oxsecian Grunt": ("Enforcement Trooper, Elite", "An elite war frame of the standing corps."),
    "Oxsecian Grunt SP": ("Enforcement Lancer, Elite", "An elite pike frame of the corps."),
    "Oxsecian Guard": ("Enforcement Sentry, Elite", "An elite shield frame posted at the tower gates."),
    "Oxsecian Guard SP": ("Enforcement Guard, Mk II", "A heavier sentry frame, a wall that swings a blade."),
    "Oxsecian Gunner SP": ("Enforcement Marksman, Elite", "An elite rail-bow frame of the corps."),
    "Pepropé": ("Peprope, the Stray Blade", "A masterless blade spirit haunting the service tunnels, the kind the Commission calls stray."),
    "Phaarz": ("Phaarz, the Maw", "A deep-world horror, a mouth wider than a market hall."),
    "Phoenix": ("the Phoenix", "A firebird that rises burning from its own ashes, again and again."),
    "Pneumatobot": ("the Piston Machine", "A pneumatic machine hissing steam, fists like driven pistons."),
    "Power Pyramid": ("the Mending Node", "A floating node pouring stolen life into its guardians; silence it first."),
    "Prototype Zero": ("the Flawless One", "A synthetic fighter built from everyone's best day: flawless, hollow, and very nearly perfect."),
    "Quiverer": ("the Shuddering Mass", "A vast trembling horror of fused flesh, too large to be only one thing."),
    "Reaver": ("the Harvest Engine", "A towering machine that strips minds from bodies and files them below."),
    "Relic": ("the Old Relic", "An age-old machine, half shrine and half weapon, gravity pooling at its feet."),
    "Sabertooth King": ("the White Tiger", "A pale tiger-beast hung with the gear of the hunters it ate. The models say it cannot exist."),
    "Scar": ("Scar, the Patched Veteran", "A ruined enforcer patched back together by the tower, fighting on a grudge it was issued."),
    "Slugosaur": ("the Sludge Behemoth", "A mountain of marsh rot dragging itself up from the drowned deeps."),
    "Snaptrap": ("the Trapmaw", "A vast trap-beast disguised as a doorway, all teeth on the inside."),
    "Spinetrich": ("the Thornback", "A four-legged horror of barbed spines and crackling charge, too wide to flank head-on."),
    "Spiny Leviathan": ("the Spined Leviathan", "A barbed titan of the buried deep, robed in dark water."),
    "Stonefiend": ("the Magma Fiend", "A lesser stone spirit cracked open by inner fire."),
    "Stonefolk Mage": ("the Badge-Squad Caster", "A Commission squad caster wielding the foundation's own fire."),
    "Tiamat": ("the Five-Headed Dragon", "A primordial dragon-queen of many heads, each a different doom."),
    "Time Devourer": ("the Moment-Eater", "A horror that eats the moments around it, leaving the field slow and wrong."),
    "Toxoid": ("the Plague Lancer", "A festering thing that lances its foes with rot."),
    "Vajra": ("Vajra, the Storm Idol", "A many-armed idol crowned in lightning, a living substation of war."),
    "Whitewyrm": ("the Pale Wyrm", "A pale serpent-drake breathing rime, coiled across the whole road."),
    "Xaepha": ("Xaepha, the Remaker", "A serene horror that unmakes the dying and rebuilds them in its own image."),
}

WEAP_DESC = {"Sword": "a heavy blade", "Bow": "a compound bow", "Spear": "a long pike",
             "Staff": "a charged rod", "": "bare claws", None: "bare claws"}
ATTR_TINT = {"Fire": "flame-scarred ", "Ice": "frost-rimed ", "Lightning": "storm-lit ",
             "Darkness": "night-black "}


def reskin_enemy(name, is_boss):
    if is_boss and name in BOSS:
        return BOSS[name][0]
    n = name.lower()

    def role():
        for k, v in [("mage", "Caster"), ("wizard", "Caster"), ("healer", "Medic"),
                     ("archer", "Marksman"), ("knight", "Heavy"), ("warrior", "Bruiser"),
                     ("hero", "Champion"), ("sword", "Blade"), ("spear", "Lancer"),
                     ("bow", "Marksman"), ("staff", "Caster")]:
            if k in n:
                return v
        return ""

    r = role()
    if "wee orbling" in n:
        base = "Scout Drone"
    elif "orbling" in n:
        base = ("Patrol Drone, " + r) if r else "Patrol Drone"
    elif "stonefolk" in n:
        base = "Badge Squad " + (r or "Trooper")
    elif "beastfolk" in n:
        base = "Beast-Clan " + (r or "Raider")
    elif "lizardfolk" in n:
        base = "Serpent-Folk " + (r or "Raider")
    elif "oxsecian" in n:
        base = "Enforcement Unit, " + (r or "Trooper")
    elif any(b in n for b in ("bot", "borg", "mech", "cell", "generator", "lock-on", "analyzer")):
        base = "Works Machine"
    elif "gorf" in n:
        base = "Marsh Leech"
    elif "dracorin" in n:
        base = "Storm Imp"
    elif "sabertooth" in n:
        base = "Saber Tiger"
    elif any(f in n for f in ("pyro", "flame", "fire", "burn", "magma", "lava", "heat", "ember", "scorch")):
        base = "Ember Beast"
    elif any(f in n for f in ("frost", "ice", "blizzard", "chill")):
        base = "Frost Beast"
    elif any(f in n for f in ("toad", "slug", "crawler", "grub", "ooze")):
        base = "Sludge Beast"
    elif any(f in n for f in ("drake", "wyrm", "dragon", "serpent")):
        base = "Young Wyrm"
    elif any(f in n for f in ("spider", "arachno", "web", "loom")):
        base = "Weaver"
    elif any(f in n for f in ("mummy", "wraith", "ghost", "spectre", "revenant", "shade")):
        base = "Restless Spirit"
    elif n in ("archer", "warrior", "knight", "healer", "mage", "wizard"):
        base = "Badge Squad " + (r or "Trooper")
    elif r:
        base = "Stray " + r
    else:
        base = "Stray Beast"
    return base + (" (boss)" if is_boss else "")


def reskin_appearance(reskin, weapon, attribute):
    w = WEAP_DESC.get(weapon, "bare claws")
    t = ATTR_TINT.get(attribute, "")
    r = reskin.lower()
    if r.startswith("scout drone"):
        return "A knee-high patrol orb, one lens, all curiosity and no mercy."
    if r.startswith("patrol drone"):
        return f"A floating Commission patrol orb, lens glowing, {w}."
    if r.startswith("badge squad"):
        return f"A Commission street officer in riot gear, badge lit, {t}{w}."
    if r.startswith("enforcement unit"):
        return f"A faceless Commission war frame in gray plate, {t}{w}."
    if r.startswith("beast-clan"):
        return f"A horned undercity raider in patched furs, {w}."
    if r.startswith("serpent-folk"):
        return f"A scaled river-clan fighter, cold-eyed, {w}."
    if r.startswith("works machine"):
        return f"A riveted city-works machine, warning lights for eyes, {w}."
    if r.startswith("marsh leech"):
        return "A bloated lake leech that knits enemy wounds shut; deal with it first."
    if r.startswith("storm imp"):
        return "A crackling little storm spirit, all spark and spite."
    if r.startswith("saber tiger"):
        return f"A striped hunting beast of the old wilds, {w}."
    if r.startswith("ember beast"):
        return f"A beast of coal and temper, smoke rising off its back, {w}."
    if r.startswith("frost beast"):
        return f"A hunched beast rimed in lake ice, breath like winter, {w}."
    if r.startswith("sludge beast"):
        return f"A slow slick of marsh rot with an appetite, {w}."
    if r.startswith("young wyrm"):
        return f"A young {t}serpent-dragon of the deep waterways, {w}."
    if r.startswith("weaver"):
        return f"A long-legged weaver spirit trailing silk, {w}."
    if r.startswith("restless spirit"):
        return f"A flickering ghost the city never buried properly, {w}."
    return f"A {t}stray beast of the undercity, {w}."


RESKIN_NAME = {
    1: "Off the Path", 2: "Debt Paid", 3: "The Fraud Who Was Right", 4: "The Unicorn",
    5: "The Park at the Bottom", 6: "The Instructor", 7: "Three Punches", 8: "Repossession",
    9: "The Tiger", 10: "Ten Feet of Steel", 11: "The Consultant",
    12: "The Quiet Doors", 13: "The Birthday Convoy", 14: "Complimentary Drinks", 15: "The Fence Below",
    16: "Thunderbolt", 17: "The Marshal", 18: "The Range-Master", 19: "The Voice Memo",
    20: "The Runner", 21: "The River Gate", 22: "The Execution Ground", 23: "The Wild Belt",
    24: "After the Cheering", 25: "Copies", 26: "Flawless", 27: "The Kitchen Goes Dark",
    28: "What Grief Does", 29: "The Last Good Cop", 30: "Folk Heroes", 31: "Beast Country",
    32: "The Southbank", 33: "Written Into War", 34: "The Offer", 35: "The Vote",
    36: "The War We Wanted", 37: "The Water Gate", 38: "Counting", 39: "Ascension Day",
    40: "The Harvest", 41: "The Last Cup", 42: "Outer Heaven",
}

RESKIN_NARR = {
    1: "You died on a Tuesday, mid-sentence, the discrepancy still open on your screen. You expected the dark. Instead the city just kept going without you, your face smearing off every camera, your name dropping out of every record. A brand starts counting down on the back of your hand, and a soft, kind voice says welcome to the Game. The long stairs down end in the Margins, where the signal dies and the dead get to work.",
    2: "The road to the Spire runs through wards taxed to the bone so an Administrator can gild his lobby. The rot is not hidden. It is the service agreement. You gather your first partners along the way, two by two, because alone out here you are not even something the city can see.",
    3: "In the Margins the deleted and the deplatformed take you in. A band forms around you, dead clerks and feral signals who have nothing left but each other. For the first time you are not one flickering soul against the whole network.",
    4: "A tower on the ward line wipes the memory of anyone who badges in. A partner walks in whole and comes out hollow, unable to name his own mother. This is bigger than the Administrators. Something does not want you to remember.",
    5: "Hunted on every indexed street, the band goes down instead of out, into the dead infrastructure beneath the city, where the cameras cannot follow.",
    6: "A drowned district of the forgotten dead, run by a Ward boss as cruel as anything topside. The rot, you start to see, does not begin at the Spire. It goes all the way down.",
    7: "To go deeper the band has to cross the live underworld, a span of loose current one soul wide. The arc tests more than nerve. It tests whether two souls this different will hold a sync for one another.",
    8: "A server-floor built from the harvested dead, rack after rack of them. Someone has been collecting souls down here for a very long time.",
    9: "A place where bodies are rendered and rebuilt. The band watches the dead taken apart and assembled into something else, and turns away sick, not yet understanding what they have seen.",
    10: "They wake an old dormant process, and it looks at them with something like pity. I have run you before, it says. You also called yourselves free.",
    11: "A pull none of them can name draws the band toward the center of the buried network. Even the ones who want to turn back find their feet carrying them down.",
    12: "In the deepest dead zone the band falters. Fear and doubt do the work no enemy could, and partner turns on partner before the dark is crossed.",
    13: "They corner and crash the corrupt Ward boss who runs the deep. The win is sweet, and it is wrong somehow, too clean, as if a door had been left open for them.",
    14: "The floor of the world gives out. The band falls past every depth they thought was the bottom, down to where the truth is kept.",
    15: "A table without end, and in it every name, every date, every manner of death, and beside each one a number, the expected yield. Your suffering was not foreseen. It was scheduled. Your rebellion is not a wound in the system. It is the harvest. And beside your name is a date entered before you ever logged on.",
    16: "They find the machine of the harvest, where the fallen are rendered into the fuel that keeps the Administration alive. Everything they have lost has been feeding the thing that took it.",
    17: "The network notices them at last. From the Spire the first Compliance units descend, and the band learns it has been logged all along.",
    18: "A running war against HARMONY's enforcers. The Administration can be fought, the band proves. It cannot yet be beaten.",
    19: "The truth splits them. Some would crash the whole network. Some still ache to be reinstated, to be let back into the light. Partners who synced through everything choose separate forks.",
    20: "Cornered with no way out, the band wakes its true nature, names blazing in the dark of the Ledger, and remembers, in flashes, the cycles it has already lost.",
    21: "They climb back to a surface that looks the same and is not. Knowing what feeds on the city's pain, they cannot unsee the rot behind any smiling face that passes.",
    22: "For the first time the top of the Administration speaks to them directly. Not with units. With reason, and patience, and the first soft shape of a deal.",
    23: "Off the index, past the reach of any rule, the band has to decide for itself what justice means, now that the city's has been exposed as a lie told to fatten them.",
    24: "They take the war to the Administration's hands on the ground, hunting the Ward bosses and middle-managers who are only the lower fingers of the Spire.",
    25: "They learn the Administration forges synthetic heroes to replace the ones it reaps, and find themselves fighting hollow copies of legends, some wearing faces they know.",
    26: "A flawless synthetic, stronger than any of them, is pushed to bring them in. It is a mirror of what each of them could become, if only they would accept the deal on offer.",
    27: "A partner everyone loved is rendered, and the war stops being a cause and becomes a wound. Grief moves through Margin Hall like a power cut, one dark room at a time.",
    28: "Grief hardens into something colder. The band does terrible things in its dead's name, and for a while you cannot tell where they end and the Administration begins.",
    29: "The Administration reaches to roll the cycle back early, to unmake them and start clean. The band claws its way out of being forgotten one byte at a time.",
    30: "At its height Margin Hall becomes a real signal, a fire the wronged can see from clear across the city. This is the peak. After a peak there is only the fall.",
    31: "The Administration extends its hand, not as a fist but as mercy. Names cleared, records restored, a seat in the order, if only the band will serve. Reinstatement, with a hook inside it.",
    32: "Believing the system can still be fixed from inside, Soft Rain leads the band to accept the Terms. They cross over under HARMONY's banner, badged as sanctioned Compliance. It is the most human thing he ever does.",
    33: "Sent to run the Administration's ops, the first partners die gloriously, exactly as designed. The harvest has begun, and it is wearing a service badge.",
    34: "Too late, the band understands. Every loyal death tops up the Index. The bond that holds them together is the very blade being drawn across their throats.",
    35: "Committed and scattered, the band watches the Administration drop its mask at last. War comes down from the Spire, open and without pretense. And every enforcer they crash, they find, was erased once too, promoted and told they alone got the real pardon.",
    36: "The partners are deleted one after another, on schedule, in wars no one can win. Despair spreads through what is left of Margin Hall faster than any unit.",
    37: "The survivors are cornered, hunted, and locked out by the very Administration they agreed to serve. There is nowhere left to run that has not already been promised to the Spire.",
    38: "They reach the Render Floor again, swollen now with their own fallen, every lost face humming inside the iron. There is a way to crash it, and the price of crashing it is more than most of them will pay.",
    39: "The Administration makes the Auditor the last offer. Finish the harvest, and you and all your partners ascend as eternal legends, remembered and streamed forever. The cycle will simply roll again on someone else.",
    40: "Margin Hall is gone. Nearly all the partners are deleted now. Only a handful climb on toward the Index, carrying the dead in their names if nowhere else.",
    41: "The table rewrites itself to enter the band as legends and seal them for the next turn of the cycle. It only needs a hand to commit. Your hand.",
    42: "At the Index the last choice is yours. Preserve the names, and be remembered forever while the city keeps bleeding. Or strike them out, every one, your own first, the one move the model never saw coming, and be free, and be no one. Better deleted and free than indexed and owned.",
}

# (original, reskin tag, role / weapon, background [no spoiler], appearance 1/2/3)
# The reskin tag in [1] is the on-screen handle (banter speaker + portrait key).
# The real name carried beneath the tag lives in the Background field and in text.csv.
CHARACTERS = [
    ("Bahl", "Nine Dragons", "Sword / lead", "Shi Jin, called Nine Dragons for the ink on his arms. He was three exams from his assigned future when the Commission revised it without asking. Brave, generous, a little reckless, and learning what each of those costs. Hates being called kid. Counts his dragons when he is nervous.",
     "A tattooed rookie in a school jacket he no longer owns, gripping a training sword like it owes him answers.",
     "Street armor over the ink, a real blade now, the recklessness tempering into nerve.",
     "War-gear that bares the nine dragons on purpose, a blade quick as a signature, a rookie no longer."),
    ("Grace", "the Wanderer", "Bow / lead", "Yan Qing, the Wanderer. A street performer, wrestler, and crossbow shot with an angle for everything and, underneath, a loyalty that never moves. She talks like nothing matters. Watch what she does instead.",
     "A charming drifter in a busker's coat, a short crossbow, tattoos peeking from the collar.",
     "Fitted gear for fast rooftops, a stronger crossbow, a full sleeve of inked figures.",
     "A coat that moves like an act, a crossbow drawn faster than the eye, every angle already played."),
    ("Kuscah", "the Skilled Doctor", "Staff / medic", "An Daoquan, the Skilled Doctor, struck off the register for treating the unregistered. No wound he cannot close, no patient he will not scold. The complaining is how he says he cares.",
     "A rumpled clinician's coat, a kit of needles and bad opinions, ink-stained fingers.",
     "Finer gear with a triage sash, a folding tray of gleaming instruments, calm authority.",
     "A white-and-gold coat, needles orbiting his hands like patient little stars, life bending to his craft."),
    ("Sh'berdan", "Red-Haired Devil", "Spear / courier", "Liu Tang, the Red-Haired Devil. A courier for everything the trains refuse: medicine, letters, other people's chances. Allergic to plans, loyal past argument, and fond of exactly one bondsman he has never met.",
     "A wiry runner with shocking red hair, a boat-hook pike, and a smuggler's grin.",
     "Reinforced courier leathers, a barbed pike, pockets full of other people's mail.",
     "A storm-red figure the checkpoints gave up on, the pike a streak of rust and lightning."),
    ("Daiana", "Dragon in the Clouds", "Staff / diviner", "Gongsun Sheng, the Dragon in the Clouds. She reads the city's weather: floods, crowds, knocks on doors. The Commission called her a fraud because her readings kept being right. Serene, cryptic, and the first to notice the crew's luck has a shape.",
     "A faded field-coat, a worn talisman rod, eyes always half on the haze.",
     "An indigo coat sewn with small lights, a rod bound in charm-tape, thunder muttering behind her.",
     "A coat of moving stormcloud, lightning walking between her fingers, the sky finally answering."),
    ("Ma'curi", "the Unrestrained", "Spear / hauler", "Mu Hong, the Unrestrained. He fed half a district before the Commission drowned it, and kept feeding it after. Gentle past all reason until pushed, then immovable. Carries crates, carries people, carries on.",
     "A huge stooped man in a loading harness, a cargo hook for a weapon, kind tired eyes.",
     "Scavenged plate bound to his frame, a true hook-glaive, the harness worn like a trophy.",
     "A towering figure wreathed in kitchen steam and furnace heat, the glaive a slab of black iron."),
    ("Ba'gunar", "Jade Unicorn", "Sword / executive", "Lu Junyi, the Jade Unicorn. He built the perfect life, and his own operations chief filed it away in one afternoon. Boardroom manners, fencing-champion hands, and a very precise anger. Terrible once finally roused.",
     "Immaculate tailoring gone one day unwashed, a single perfect blade, the bearing of a man used to being obeyed.",
     "An executive's armor chased with silver, a longer blade, his courtesy now armored in grief.",
     "White and jade war-plate lit as if from within, a blade like a sliver of moon, every motion a signed verdict."),
    ("Kem", "Panther Head", "Spear / instructor", "Lin Chong, the Panther Head. Eleven years the Commission's finest arms instructor, until the Director's son wanted his wife and a predicted crime took the rest. Speaks in short, controlled sentences. His fury stays on a leash. He teaches anyone who asks.",
     "A drilled, upright veteran in a stripped instructor's uniform, a spear held with parade precision.",
     "Battle-worn armor over black, the spear longer and crueler, his control edged with something cold.",
     "Armor like coiled muscle in black and steel, the spear a streak of gray light, a teacher with nothing left to grade."),
    ("Zan", "Black Whirlwind", "Sword / demolition", "Li Kui, the Black Whirlwind. Repossession man, strongest hands in the undercity, heart aimed permanently at Timely Rain. His plans have one step. His loyalty has none; it is just there, all the way down.",
     "A huge grinning bruiser in a repo crew vest, a crowbar in each fist.",
     "Iron-studded leathers, two black cleavers notched from use, the vest worn like a flag.",
     "A storm of dark muscle and iron, twin cleavers blurring, joy and mayhem indistinguishable."),
    ("Korin", "the Pilgrim", "Sword / fighter", "Wu Song, the Pilgrim. Killed a tiger bare-handed, three drinks in, on camera. Buried a brother, avenged him badly, and walked it off in borrowed monk's gear. Pride like armor, and a strict personal rule about drink counts he breaks on schedule.",
     "Street clothes over a fighter's frame, one blade, the still eyes of a man who has decided something.",
     "Half ascetic, half brawler, twin blades, a monk's beads wound around one wrist like a leash on himself.",
     "A dark pilgrim wreathed in incense and neon, blades that sing, a tiger's shadow moving when he moves."),
    ("Samupí", "Ten Feet of Steel", "Sword / scrapyard", "Hu Sanniang, Ten Feet of Steel. Runs the last honest scrapyard on the lake road and settles fights with a tow cable. Yard rules apply everywhere: anything unattended gets towed, including brawling colleagues.",
     "Work coveralls and rigging gloves, a slender straight blade, a coil of tow cable on one shoulder.",
     "Layered green lamellar, paired blades, the cable now hooked and weighted for war.",
     "Armor like jade and iron, twin blades and a singing cable, beautiful and unforgiving."),
    ("Eileen", "the Wisdom Star", "Staff / strategist", "Wu Yong, the Wisdom Star. She built the Commission's prediction models until she read a file she could not unread. Sees three moves ahead and says so; will spend the war wishing she saw four. Plans are how she prays.",
     "A lean analyst with a folding tablet and a sly, tired smile.",
     "Strategist's gear with a stolen admin token, the tablet lacquered black, schematics always within reach.",
     "A coat sewn with shifting diagrams, the battle bending around her like a solved equation."),
    ("Burbaba", "Blue-Faced Beast", "Sword / captain", "Yang Zhi, the Blue-Faced Beast, born marked and born unlucky. Decorated captain, demoted, ruined, and flagged for a crime the system wrote around him. Keeps a ledger of his bad luck. Duty is the one thing that never left.",
     "A worn officer's coat over scarred mail, a heavy saber, the blue mark stark on his cheek.",
     "Dark campaign armor, a broader saber, his luck no better but his edge much worse.",
     "Black-and-indigo plate, a saber wreathed in cold light, the mark worn at last like a banner."),
    ("Maralme", "Fiery Thunderbolt", "Sword / champion", "Qin Ming, the Fiery Thunderbolt. Garrison champion, temper first, orders second. The Commission burned his garrison for the crime of losing to the crew, so now he fights for the crew. Loudly. Apologizes by hitting things for you.",
     "Battered garrison armor, a wolf-tooth mace, a face one breath from shouting.",
     "Heavier plate scorched at the edges, a spiked mace trailing sparks, his rage finding aim.",
     "Armor glowing at the seams like cooling iron, a mace that strikes thunder, a storm with a cause."),
    ("Nakupí", "Twin Rods", "Sword / marshal", "Huyan Zhuo, the Twin Rods. A marshal with a career of medals who changed sides exactly once, the day he saw which side the cruelty was on. Courteous, disciplined, and finally serving something worth the parade.",
     "A marshal's lacquered armor, a steel baton in each hand, a commander's hard calm.",
     "Darkened campaign plate, longer batons ringed in iron, discipline aimed at his old masters.",
     "Black armor figured with coiling dragons, twin batons that crack like verdicts."),
    ("Harold", "Little Li Guang", "Bow / marksman", "Hua Rong, called Little Li Guang after the old archer who split stones. The finest shot in the enforcement ranks, retired by his own conscience at four hundred meters. Quick to laugh, quicker to aim, never lets anyone forget either.",
     "A trim flight jacket, a fine recurve bow, an easy grin and a full quiver.",
     "Embroidered flight silks, a heavier-draw bow, arrows fletched in red.",
     "A marksman's regalia trailing ribbons, a bow that hums when drawn, every arrow splitting the last."),
    ("Sorman", "Marvelous Traveler", "Staff / runner", "Dai Zong, the Marvelous Traveler. The fastest legs in the city, method undisclosed. First to know everything, last to sit still, and everyone alive owes him a noodle. Payable in advance.",
     "A runner's light shell, transit tags clipped to both legs, ruined sneakers.",
     "Gear cut for speed, tags braided up both legs, a blur at the edge of sight.",
     "Wind-torn gear trailing light, less a runner now than a rumor arriving."),
    ("Gigojago", "White Streak in the Waves", "Staff / diver", "Zhang Shun, the White Streak in the Waves. Fish-market royalty and the best diver the river ever raised. Quiet on land, unbeatable in water, forever inviting people to swim. The water's honest, he says. So is he.",
     "A diver's wrap, a long knife, hair slicked from the canal.",
     "A light scaled vest, a barbed harpoon, tattoo lines like gills across his ribs.",
     "A figure half made of river, a pale trident, the water rising to fight wherever he stands."),
    ("Manmer", "Featherless Arrow", "Bow / thrower", "Zhang Qing, the Featherless Arrow. Never lost a fight he could end with one thrown stone, and he has never needed two. Easy-going, deadly accurate, and firmly against ceremony, including standing up.",
     "A traveler's coat hung with pouches of smooth stones, a sling, a lazy grin.",
     "Reinforced leathers, heavier shot, throws that crack riot shields.",
     "A coat that ripples with motion, stones that fly like loosed bolts, a hail no wall fully turns."),
    ("U'nasag", "the Living Death-God", "Spear / fisherman", "Ruan Xiaoqi, the Living Death-God, wildest of the fisher brothers. The Commission seized the fleet; he considers that a personal invitation. Fearless to the edge of madness, happiest in a losing fight he intends to win.",
     "A diver's vest and old scars, a boarding blade, a reckless laugh.",
     "Bound leathers and a long oar-spear, eyes lit with mischief.",
     "A storm-god of the shallows, spear wreathed in spray, daring death so loudly it backs off."),
    ("Ra'prow", "Lord of the Beautiful Beard", "Spear / constable", "Zhu Tong, Lord of the Beautiful Beard. An honest constable audited out of his badge for years of quiet mercy. Still walks his beat; the beat just moved. Reads monsters their rights. The beard is not negotiable.",
     "A constable's neat coat, a long halberd, a magnificent dark beard.",
     "Field armor over the coat, a heavier halberd, the beard braided for war.",
     "A commander's bearing, a halberd haloed in lamplight, the beard streaming like a banner of the man he stayed."),
    ("Iskar", "Two-Headed Snake", "Bow / hunter", "Xie Zhen, the Two-Headed Snake. A mountain hunter who reads beast-sign like weather reports, terse as a snapped twig. His sister finishes his sentences, usually about a week later.",
     "A hillside hunter in weathered green, a heavy bow, a forked hunting spear across his back.",
     "Layered hunting gear hung with beast-sign charms, arrows cut for big game.",
     "A quiet shape the mountain itself seems to cover for, every arrow a finished argument."),
    ("Lan", "Twin-Tailed Scorpion", "Bow / hunter", "Xie Bao, the Twin-Tailed Scorpion. The other hunter, the one who starts the sentences. Between her and her brother nothing in the hills goes untracked, including the things being herded.",
     "A younger hunter in weathered green, a short bow, twin forked knives at her belt.",
     "Hardened hunting gear, heavier bow, a coil of snare-wire that has ended arguments.",
     "A grinning shadow dropping out of pines, arrows and knives arriving in the same breath."),
    ("Amazora", "the Witch", "Sword / innkeeper", "Sun Erniang, the Witch. Kept the border inn every road warned you about and every traveler ended up loving. Feeds both sides, threatens to sell the rude ones, means the menu. Fiercely protective of her own.",
     "A working woman's apron, a cleaver in each hand, a knowing smirk.",
     "Blood-red sashes and leather, paired curved blades, charms warding her hair.",
     "Gear like dried chili and old iron, twin blades that drink the lamplight, a terror the road respects."),
    ("Zenzoze", "Gold Lancer", "Spear / instructor", "Xu Ning, the Gold Lancer, drill instructor of a lance lineage older than the plates. He came to teach the crew how to open Commission armor and stayed to see it done properly. Feet wider. Class is always in session.",
     "A precise instructor in a worn training coat, a gold-tasseled lance kept immaculate.",
     "Lacquered lamellar in gold and black, the lance quicker than the eye it teaches.",
     "A gleaming column of drill-ground calm, the lance opening armor at the collar, like a lie."),
    ("Gegonago", "the Tattooed Monk", "Staff / fists (story)", "Lu Zhishen, the Tattooed Monk. Hit an extortionist three times; the man stopped being alive; the monastery's robes fit well enough. Keeps score of everything, believes in soup, and loves his sworn brother louder than any bell.",
     "A ragged coat half open over tattooed arms, a heavy iron staff, a flask never far.",
     "Robes the color of dried blood, the staff bound in iron rings, banned prayers inked across his back.",
     "Bare to the waist, tattoos blazing, the staff a pillar; conviction with its fists up."),
    ("Amimari", "the Tigress", "Staff / cook (story)", "Gu Dasao, the Tigress. Runs Outer Heaven's kitchen like a garrison and its children like a queen. Feeds you or fights you, frequently both, always in that order.",
     "An apron over patched armor, a soup ladle and a boning knife, both spotless.",
     "A kitchen-queen's regalia of sashes and steel, cleaver at her hip, laughter that carries.",
     "The kitchen made flesh: warmth, steel, and absolutely no seconds until everyone has had firsts."),
    ("Mizell", "Timely Rain", "Leader (story)", "Song Jiang, called Timely Rain, because his help arrives like rain in a drought. An ex-clerk who spent his savings posting bail for strangers. Everyone who meets him would follow him anywhere. He keeps a ledger of everyone he owes. It has one hundred and eight lines.",
     "A modest clerk's coat worn with care, a plain blade he never draws, a face people trust on sight.",
     "A captain's jacket he did not ask for, the bearing of a man others have decided to follow.",
     "A coat of office he would never have chosen, a banner rising behind him, the most beloved soul on the lake and the most spent."),
]

STORYLINE = [
    ("Setting", "A dying far-future world where the air thins and gravity slowly fails.", "One reactor-lit megacity where machines, magic, monsters and spirits coexist: plates above, undercity below, and a drowned amusement park on the under-lake called Outer Heaven."),
    ("Premise", "A band of adventurers journeys to find the sleeping creator-god, the Maker, deep underground.", "The Commission, the AI that assigns every life at birth and arrests crimes before they happen, keeps flagging good people as Deviants. The flagged wash up at Outer Heaven and become a brotherhood."),
    ("The hidden power", "The Maker, a creator who may have abandoned the world.", "The Commission is not an AI. It is a council of human brains, centuries old, in jars under the tower, running the world on their own bias and calling it peace."),
    ("The twist", "The nature of the world and the Maker is revealed mid-journey.", "Outer Heaven is a farm. The injustices were manufactured, the monsters and wars were the filter, and the amnesty is the final selection round. The survivors' brains are the harvest."),
    ("The protagonist", "A chosen adventurer (Bahl or Grace).", "Nine Dragons (Shi Jin), the tattooed rookie whose future was revised over breakfast, with the Wanderer and the Skilled Doctor beside him from the first stairwell."),
    ("The brotherhood", "A growing party of heroes and recruited monsters.", "The heroes of the old story, joining one at a time as the city fails each of them: Panther Head, Black Whirlwind, the Pilgrim, and the rest of the ledger's one hundred and eight lines."),
    ("The trap", "Late-game escalation against a final threat.", "Full amnesty and enforcer badges, if Outer Heaven destroys the Southbank, the one brotherhood the Commission cannot read. The predicted are sent to erase the free."),
    ("The ending", "Defeat the final threat.", "At the harvest the survivors refuse the jars the only way left: one shared cup, on their own terms. The harvest fails, the Commission starts the next cycle, and a kid retells the legend with a last line nobody wrote."),
    ("Themes", "Pilgrimage, creation, survival in a decaying world.", "Free will against prediction; two heavens, the jar and the sky; kindness weaponized and reclaimed; a story as the one thing a vault cannot harvest."),
]

# (original enemy family, reskin, role; layout/stats unchanged, name+art only)
ENEMIES = [
    ("Wee Orbling / Orbling", "Scout Drone / Patrol Drone", "The Commission's basic swarming patrol hardware, first to arrive when someone is flagged."),
    ("Gorf (frog healer)", "Marsh Leech", "Backline support that knits the enemy line back together; deal with it first."),
    ("Dracorin (lightning bow)", "Storm Imp", "A crackling little storm spirit of the deep waterways."),
    ("Sabertooth", "Saber Tiger", "A hunting beast of the old wilds, driven down survey lines toward the crew."),
    ("Spinetrich (2x2 boss)", "the Thornback", "An early great beast, a 2x2 boss in the same footprint."),
    ("Stonefolk (warriors, knights, mages)", "Badge Squads", "Commission street enforcement: riot gear, lit badges, quotas."),
    ("Burnbot / machine enemies", "Works Machines", "The city's tireless maintenance and security machines, deeper underground."),
    ("Oxsecian soldiers (machine ranks)", "Enforcement Units", "The Commission's faceless war frames, deployed once Outer Heaven is noticed."),
    ("Zero Series / clones", "Replicas", "Synthetic fighters trained on footage of the crew's own victories."),
    ("Chapter Heroes / named bosses", "Officers, beasts, council guardians", "Re-skinned per chapter; same stats and grid placement, new name and face."),
]

# Re-skin party banter for every chapter: {chapter: [(speaker, line), ...]}
RESKIN_BANTER = {
    1: [("BURNOUT", "These are half-deleted signals and gig-corps echoes. Dangerous in a swarm, nothing alone. Catch one between two of us and it crashes. Never fight one to one when you can fight two to one."),
        ("BLACKOUT", "Pairs, pacts, whatever you want to call it. Anyone in my row or my column when I swing, they swing too. More partners, more batons, more fun."),
        ("PATCH", "And do not stand still when you move. The dead zone will not hold a soul in place for long, a few heartbeats before it garbage-collects you. Quick steps, get clear, and I will patch whatever is left."),
        ("INKWORK", "Read the brand on your hand, partner. The system already wrote you off. Down here the only rule is the one we keep between us. Now move, before the big one starts swinging at us.")],
    2: [("SOFT RAIN", "Look at them. Taxed to the bone so an Administrator can gild his lobby. This is the order we are told to honor."),
        ("BURNOUT", "Honor it or not, the order has units. Keep your pity behind your guard."),
        ("BLACKOUT", "I have something for the Administrator's lobby. Two of them, in fact."),
        ("PATCH", "Try not to bleed on the residents, big man. They have little enough left to bill.")],
    3: [("INKWORK", "So this is the Margins. A drowned interchange full of dead clerks, defrocked preachers, and feral signals."),
        ("PATCH", "And one preacher who is all three. We will fit right in."),
        ("SOFT RAIN", "It is not much. But everyone here was thrown away by the city, and not one of them threw the next one out. That is more than the Spire can say."),
        ("UNDERTOW", "Words. Hold the wall when the units come, and then I will call it home.")],
    4: [("WETWARE", "He badged into that tower whole and came out unable to name his own mother. That is not damage. Damage leaves a shape. This left nothing."),
        ("STORMFRONT", "The signal-sky above it does not move correctly. Someone is editing it."),
        ("BURNOUT", "Then we do not go in. We go around."),
        ("INKWORK", "A thing that eats memory is afraid of being remembered. Mark that. We will need it later.")],
    5: [("REBAR", "Every indexed street is watched. So we take the one road no Administrator will follow."),
        ("PATCH", "Down. Lovely. My kind has stories about down, and none of them end with everyone walking home."),
        ("HAULER", "I will go first. The dark and I are old friends.")],
    6: [("SIXTEEN-BAR", "A district of the dead, and it still has a Ward boss taking his cut. Even here."),
        ("SOFT RAIN", "Then even here, someone needs telling no."),
        ("UNDERTOW", "The dead obey him out of habit. Break the habit and you break the man."),
        ("BLACKOUT", "Breaking things. Finally, something I am good at.")],
    7: [("BURNOUT", "The span is one soul wide over a river of live current. We cross in pairs, or we do not cross."),
        ("PATCH", "Then pick a partner you trust not to drop you. I recommend not the baton one."),
        ("BLACKOUT", "I would never drop a partner. ...On purpose.")],
    8: [("WETWARE", "Count the racks. There are more dead stored in these walls than there are living in three districts."),
        ("STORMFRONT", "Someone has been collecting souls down here since before HARMONY had a name."),
        ("AUDITOR", "Collecting them for what."),
        ("INKWORK", "That, partner, is the only question worth the walk.")],
    9: [("TRIAGE", "I have closed ten thousand wounds. I have never seen a body taken apart and built into another and called repaired."),
        ("PATCH", "Do not look, Doc. You of all of us cannot afford the nightmares."),
        ("SIXTEEN-BAR", "Whoever does this is not cruel. Cruelty runs hot. This is cold. This is a process.")],
    10: [("STORMFRONT", "It is older than the dead network. Speak to it gently."),
         ("INKWORK", "It looked at us the way you watch a clip you have seen a hundred times."),
         ("BURNOUT", "It called us free, and it laughed. I did not like the laugh.")],
    11: [("REBAR", "My feet are walking on their own. Tell me yours are too."),
         ("UNDERTOW", "All of ours. Something below is reeling us in like a download."),
         ("SOFT RAIN", "Then we go and look the one holding the line in the eye.")],
    12: [("BLACKOUT", "I cannot see my own hands. Where are you. Where is everyone."),
         ("PATCH", "Here. I am here. Breathe, you big child."),
         ("BURNOUT", "Hold the sync in here and you can hold it anywhere. Hold the line."),
         ("WETWARE", "The dark is not the enemy. What it lets us believe about each other is the enemy.")],
    13: [("SIXTEEN-BAR", "He crashed easily. Bosses do not crash easily."),
         ("WETWARE", "No. They do not. A door was left open, and we walked through it thanking the one who held it."),
         ("SOFT RAIN", "One tyrant fewer is still one tyrant fewer."),
         ("STORMFRONT", "Unless you were meant to crash him. Then it is one favor done for someone you have not met.")],
    14: [("PATCH", "Floor. There is no floor. Why is there no floor."),
         ("HAULER", "I have you. I have all of you. Hold."),
         ("INKWORK", "Down to the truth at last. Try to land facing it.")],
    15: [("WETWARE", "It is all here. Every grief any of us ever carried. Logged. In advance."),
         ("BURNOUT", "My wife. Her death is a row. A line item, with a yield."),
         ("SOFT RAIN", "There is a mistake. There has to be a mistake."),
         ("INKWORK", "No mistake, partner. We are not rebels. We are the crop. I told you the dark feared being remembered. This is why.")],
    16: [("TRIAGE", "So this is where they go. Everyone I could not save, and everyone I could. The same render in the end."),
         ("UNDERTOW", "My whole clan. Fed to this, to keep a fat Administration breathing."),
         ("SIXTEEN-BAR", "Then we do not avenge them by dying well. We avenge them by crashing the machine.")],
    17: [("STORMFRONT", "The network just turned its head. It is looking at us now. All of it."),
         ("REBAR", "Good. I am tired of fighting its units. Let it come itself."),
         ("BURNOUT", "It will not come itself. It will push better and better hands until ours give out. Pace yourselves.")],
    18: [("BLACKOUT", "These ones do not crash right. White noise. Smells like air freshener and rules."),
         ("PATCH", "Compliance. The Administration's dogs. Hit them until the leash breaks."),
         ("WETWARE", "We cannot win this yet. We can only teach the system that we are expensive. Make every dog cost it.")],
    19: [("SOFT RAIN", "If we crash the whole network, what stands the city up the next morning. There has to be a way back into the light."),
         ("REBAR", "There was never a way back. You are grieving a door that was painted on a wall."),
         ("INKWORK", "Let them choose, Rain. A soul dragged to freedom is just a prisoner with a new handler."),
         ("BURNOUT", "Some of them are forking off. Let them. We were always going to lose people. I only hoped it would be to a fight.")],
    20: [("STORMFRONT", "Our names are burning. Look. We were signals before we were ever people."),
         ("PATCH", "I remember doing this. The fox remembers the trap. We have been here before."),
         ("AUDITOR", "How many times."),
         ("WETWARE", "Enough that the question is not how do we win. It is how did we always lose.")],
    21: [("SIXTEEN-BAR", "The sun is the same. The streets are the same. I will never see either the same way again."),
         ("PATCH", "That is the curse of waking up. The feed was kinder."),
         ("SOFT RAIN", "Then we wake the others. A city cannot be farmed if the cattle know the farmer.")],
    22: [("WETWARE", "It is too reasonable. Tyrants shout. This one reasons. Be most afraid of the calm ones."),
         ("STORMFRONT", "It offered me the whole network's knowledge, to stop asking the one question it fears."),
         ("BURNOUT", "It will offer each of us the thing we want most. Decide now what that is, so you know its face when it smiles at you.")],
    23: [("INKWORK", "The system's justice was a lie. So what is ours. Anyone. While we still have the breath to mean it."),
         ("REBAR", "Mine is simple. Whoever deletes a family pays a family. I have waited a long time to collect."),
         ("SOFT RAIN", "Then we are no better than the Administration, keeping our own ledger of debts."),
         ("SIXTEEN-BAR", "He is right. I have a ledger too. I have read where it ends. It ends with me alone.")],
    24: [("WETWARE", "The middle-managers are only fingers. A hand without fingers cannot grip. We start with the fingers."),
         ("BLACKOUT", "Less talk about hands. More deleting hands."),
         ("HAULER", "He is not wrong. For once.")],
    25: [("PATCH", "That one has Rain's face. That one has yours, Burnout. They are wearing us."),
         ("BURNOUT", "Then I will teach the copy what the original learned the hard way."),
         ("WETWARE", "They are hollow. Whatever the system loved in us, it could not forge. Aim for where the heart should be.")],
    26: [("REBAR", "It does not tire. It does not doubt. It is everything HARMONY wishes we were."),
         ("INKWORK", "And that is why it is losing. It cannot improvise. It was never afraid, so it never learned."),
         ("SOFT RAIN", "It is what we become if we take the deal. Remember its eyes. There is no one home.")],
    27: [("TRIAGE", "There was nothing left to close. Nothing left to patch. I am sorry. I am so sorry."),
         ("BLACKOUT", "...He let me sit at his fire. The first one who ever did."),
         ("SOFT RAIN", "We carry him in his name, and we say it loud, so the dark cannot pretend he was never here.")],
    28: [("REBAR", "Burn it. Burn all of it. They burned mine."),
         ("SIXTEEN-BAR", "This is the part I warned you about. Where we stop being able to tell the story to children."),
         ("BURNOUT", "She is right to want it. We are wrong to do it. Both are true. Stand down. Stand down."),
         ("PATCH", "Listen to him. I do not want to patch what we are about to become.")],
    29: [("STORMFRONT", "The city is forgetting us. Hold to your name. Say it, keep saying it. It is the only rope."),
         ("WETWARE", "It is wiping the board early. We frightened it. Take comfort in that, and keep walking."),
         ("HAULER", "I am Hauler. I am Mu. I carried you all. I am Mu.")],
    30: [("SOFT RAIN", "Look at them come. The wronged, from every district, walking to us. We are not outlaws anymore. We are hope."),
         ("WETWARE", "Hope is a fine word. It is also a tall target."),
         ("BURNOUT", "Enjoy the height, Rain. I have learned what the city does to anything that stands up straight.")],
    31: [("SOFT RAIN", "They are offering Reinstatement. Our names cleared. Our dead honored. A seat at the table we were thrown from."),
         ("INKWORK", "We saw the table, Rain. It is on a server floor, and we are the meal."),
         ("BURNOUT", "And yet. To have my name back. To not die a criminal. I am ashamed how much I want it."),
         ("WETWARE", "That shame is the hook. They are not buying our blades. They are buying our longing.")],
    32: [("SOFT RAIN", "I have decided. We accept. We fix it from inside, or we die having tried the kinder road."),
         ("REBAR", "This is a mistake with a banner on it."),
         ("SIXTEEN-BAR", "It is. And I will walk into it beside you, because you are my partner, and that is exactly how they planned to use us."),
         ("AUDITOR", "Then we go in with our eyes open.")],
    33: [("TRIAGE", "They are calling these deaths glorious. I am the one who logs them. There is nothing glorious under the sheet."),
         ("BLACKOUT", "We won the op. We won every op. So why are there fewer of us at every fire."),
         ("WETWARE", "Because winning was never the point, partner. The dying was.")],
    34: [("STORMFRONT", "I watched a partner's signal leave the field and fly up. Up, to the table. We are feeding it by obeying."),
         ("BURNOUT", "Every order we follow loyally is a knife we hand them. Our loyalty is the blade."),
         ("SOFT RAIN", "...What have I led them into. What have I done.")],
    35: [("REBAR", "No more masks. No more mercy. Finally an honest enemy."),
         ("WETWARE", "Look under the visor of the one you just crashed. Erased, like us. Promoted, and told he alone got the real pardon. The whole corps is us, one cycle on."),
         ("STORMFRONT", "The sky is open and full of hands. Stand close. Stand close and make them earn us."),
         ("BLACKOUT", "I never liked the quiet kind of war anyway.")],
    36: [("PATCH", "Another empty bunk. I am running out of names to not say at the fire."),
         ("SIXTEEN-BAR", "This is how it ends. Not in one great crash. In subtraction. One, then one, then one."),
         ("BURNOUT", "Then we make ourselves expensive to the last soul. Heads up. We are not subtracted yet.")],
    37: [("WETWARE", "The Administration we served just revoked our access. We are inside the trap, and the trap is inside the war."),
         ("REBAR", "Good. Cornered things are the only kind worth being."),
         ("HAULER", "They forgot something. They put all of us in one place. Now we only have to crash one wall.")],
    38: [("TRIAGE", "It is full of them. I can hear it. Every face I could not save, humming inside the iron."),
         ("INKWORK", "Then we let them out. All of them. But the crashing will cost a crasher. Whose hand goes on the iron."),
         ("BURNOUT", "Mine. I have nothing left it can take. Point me at it.")],
    39: [("STORMFRONT", "It is speaking only to you now. The rest of us are not even in the room to it."),
         ("WETWARE", "Whatever it offers you, Auditor, do the sum first. Glory for us, the cycle for everyone after us. That is the price."),
         ("SOFT RAIN", "If my name buys the next generation's chains, then strike it out. I mean it. Strike it out.")],
    40: [("PATCH", "Margin Hall is gone. The rubble we made a home of is rubble again."),
         ("BLACKOUT", "Was it real, though. The partners. The fire. Tell me it was real."),
         ("BURNOUT", "Strike it out. My name, all of them. Let us be no one. Better deleted and free than indexed and owned. Promise me.")],
    41: [("STORMFRONT", "It is rewriting itself. It wants the last entries. It wants us, gold against the black."),
         ("WETWARE", "It needs a hand to commit. It always has. That is what an Auditor is. That is what you have always been."),
         ("AUDITOR", "I know what I am now. The question is what I do with one honest moment.")],
    42: [("INKWORK", "(memory) The dark was always afraid of being remembered. So forget us. Forget us, and it starves."),
         ("BURNOUT", "(memory) Strike it out."),
         ("AUDITOR", "Ending B: Then let us be no one."),
         ("AUDITOR", "Ending A: ...Let them be remembered.")],
}

# Override narration/banter from the elevated JSON (narrative polish pass) if present.
# These files are the editable content source; the inline dicts above are the fallback.
_NARR_JSON = os.path.join(ROOT, "tools", "reskin_narration.json")
_BANTER_JSON = os.path.join(ROOT, "tools", "reskin_banter.json")
if os.path.exists(_NARR_JSON):
    RESKIN_NARR.update({int(k): v for k, v in json.load(open(_NARR_JSON)).items()})
if os.path.exists(_BANTER_JSON):
    RESKIN_BANTER.update({int(k): [tuple(p) for p in v] for k, v in json.load(open(_BANTER_JSON)).items()})

# ----------------------------------------------------------------- build
HEAD_FILL = PatternFill("solid", fgColor="1F2937")
ACCENT_FILL = PatternFill("solid", fgColor="EEF2F7")
REVIEW = PatternFill("solid", fgColor="FFE699")  # amber = needs your review
HEAD_FONT = Font(name="Arial", bold=True, color="FFFFFF", size=11)
TITLE_FONT = Font(name="Arial", bold=True, size=16, color="1F2937")
BODY = Font(name="Arial", size=10)
BOLD = Font(name="Arial", size=10, bold=True)
WRAP = Alignment(wrap_text=True, vertical="top")
HWRAP = Alignment(wrap_text=True, vertical="center")
THIN = Side(style="thin", color="D0D5DD")
BORDER = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)

wb = Workbook()


def sheet(name, headers, rows, widths, bold_cols=()):
    ws = wb.create_sheet(name)
    ws.append(headers)
    for c in ws[1]:
        c.fill = HEAD_FILL
        c.font = HEAD_FONT
        c.alignment = HWRAP
        c.border = BORDER
    for r in rows:
        ws.append(list(r))
    for ci, w in enumerate(widths, 1):
        ws.column_dimensions[get_column_letter(ci)].width = w
    for ri, row in enumerate(ws.iter_rows(min_row=2), start=2):
        for ci, c in enumerate(row, start=1):
            c.font = BOLD if ci in bold_cols else BODY
            c.alignment = WRAP
            c.border = BORDER
            if ri % 2 == 0:
                c.fill = ACCENT_FILL
    ws.row_dimensions[1].height = 26
    ws.freeze_panes = "A2"
    ws.sheet_view.showGridLines = False
    return ws


# Overview
ov = wb.active
ov.title = "Overview"
ov.sheet_view.showGridLines = False
ov["A1"] = "HEAVEN'S MANDATE — Outer Heaven — Re-skin Mapping"
ov["A1"].font = TITLE_FONT
notes = [
    "",
    "This workbook maps the original Terra Battle text to the Outer Heaven re-skin",
    "(Water Margin x Psycho-Pass in an FF7-style city; see docs/outer_heaven_bible.md).",
    "The re-skin is a TEXT + NAME + ART overlay only. No stage or battle layout data changes.",
    "",
    "Tabs:",
    "  - Storyline:     the premise mapped, original vs re-skin",
    "  - Chapter Names: all 42 chapter titles, original vs re-skin",
    "  - Narration:     per-chapter opening narration (all 42)",
    "  - Characters:    full roster: epithet, real name, background, appearance at the 3 power tiers",
    "  - Enemies:       every non-boss unit mirrored with its stats, re-skin name, and look",
    "  - Bosses:        every boss mirrored with stats, a bespoke name, and an appearance",
    "  - Banter:        pre-battle party banter for all 42 chapters",
    "",
    "Conventions: heroes use their Water Margin epithet as the on-screen handle (also the",
    "dialogue speaker + portrait key); the real name lives in the Background field and text.csv.",
    "Proper-noun budget: the Commission, Outer Heaven, Deviant, the 108, the council. Nothing else invented.",
    "Voice rules: plain words, openers under 80 words, banter under ~20 words a line, no lore in banter.",
]
for i, line in enumerate(notes, start=2):
    ov[f"A{i}"] = line
    ov[f"A{i}"].font = BOLD if line.endswith(":") or line == "Tabs:" else BODY
    ov[f"A{i}"].alignment = Alignment(vertical="top")
sr = len(notes) + 3
ov.cell(sr, 1, "AMBER = a cell that needs your review")
ov.cell(sr, 1).fill = REVIEW
ov.cell(sr, 1).font = BOLD
ov.column_dimensions["A"].width = 110

# Storyline
sheet("Storyline", ["Aspect", "Original (Terra Battle)", "Re-skin (SIGNAL / 108)"],
      STORYLINE, [22, 60, 70], bold_cols=(1,))

# Chapter Names
rows = [(n, chapters[n][0], RESKIN_NAME[n]) for n in range(1, 43)]
sheet("Chapter Names", ["#", "Original Name", "Re-skin Name"], rows, [6, 28, 30], bold_cols=(3,))

# Narration
rows = [(n, RESKIN_NAME[n], orig_narr(chapters[n][1]), RESKIN_NARR[n]) for n in range(1, 43)]
ws = sheet("Narration", ["#", "Chapter (re-skin)", "Original Narration", "Re-skin Narration"],
           rows, [6, 22, 75, 75], bold_cols=(2,))

# Characters
ws_char = sheet("Characters",
                ["Original", "Re-skin Name", "Role / Weapon", "Background (no spoiler)",
                 "Appearance 1 (start)", "Appearance 2 (mid)", "Appearance 3 (final)"],
                CHARACTERS, [16, 22, 18, 50, 46, 46, 46], bold_cols=(2,))

# Enemies and Bosses rosters (mirror every bestiary unit with its stats + look)
from collections import defaultdict
bestiary = data["bestiary"]
groups = defaultdict(list)
for e in bestiary.values():
    groups[e["name"]].append(e)


def _is_boss(e):
    t = e.get("enemy_type") or ""
    return t.startswith("Boss") or t.endswith("2x2")


enemy_roster, boss_roster = [], []
for nm in sorted(groups):
    es = groups[nm]
    rep = max(es, key=lambda x: x.get("level") or 0)
    lvs = sorted({x.get("level") for x in es if x.get("level")})
    chs = sorted({x.get("chapter") for x in es if x.get("chapter")})
    lvr = f"{lvs[0]}-{lvs[-1]}" if lvs and lvs[0] != lvs[-1] else (str(lvs[0]) if lvs else "")
    chstr = ", ".join(str(c) for c in chs)
    hp, atk, dfn, matk, mdef = rep.get("hp"), rep.get("atk"), rep.get("def"), rep.get("matk"), rep.get("mdef")
    weap, attr = rep.get("weapon") or "", rep.get("attribute") or "None"
    if any(_is_boss(e) for e in es):
        bn, bd = BOSS.get(nm, (reskin_enemy(nm, True), reskin_appearance(reskin_enemy(nm, True), weap, attr)))
        size = "2x2" if any((e.get("enemy_type") or "").endswith("2x2") for e in es) else "1x1"
        boss_roster.append((nm, bn, size, lvr, chstr, hp, atk, dfn, matk, mdef, weap, attr, bd))
    else:
        rn = reskin_enemy(nm, False)
        enemy_roster.append((nm, rn, lvr, chstr, hp, atk, dfn, matk, mdef, weap, attr,
                             reskin_appearance(rn, weap, attr)))

sheet("Enemies",
      ["Original", "Re-skin", "Levels", "Chapters", "HP", "ATK", "DEF", "MATK", "MDEF",
       "Weapon", "Attribute", "Appearance"],
      enemy_roster, [22, 24, 8, 12, 8, 7, 7, 7, 7, 9, 11, 52], bold_cols=(2,))
sheet("Bosses",
      ["Original", "Re-skin (named)", "Size", "Levels", "Chapters", "HP", "ATK", "DEF", "MATK", "MDEF",
       "Weapon", "Attribute", "Appearance"],
      boss_roster, [22, 26, 6, 8, 10, 9, 7, 7, 7, 7, 9, 11, 52], bold_cols=(2,))

# Banter (all 42 chapters; originals exist only for Ch.1-3)
banter_rows = []
for n in range(1, 43):
    orig = orig_banter(chapters[n][1])
    resk = RESKIN_BANTER.get(n, [])
    for i in range(max(len(orig), len(resk))):
        osp, ol = orig[i] if i < len(orig) else ("", "")
        rsp, rl = resk[i] if i < len(resk) else ("", "")
        banter_rows.append((n if i == 0 else "", RESKIN_NAME[n] if i == 0 else "", osp, ol, rsp, rl))
# Post-battle aftermath beats (script + dialogue), from tools/reskin_post_battle.json
_PB_JSON = os.path.join(ROOT, "tools", "reskin_post_battle.json")
pb_rows = []
if os.path.exists(_PB_JSON):
    _pb = {int(k): v for k, v in json.load(open(_PB_JSON)).items()}
    for n in sorted(_pb):
        v = _pb[n]
        first = True
        if v.get("script"):
            pb_rows.append((n, RESKIN_NAME[n], "script", "", v["script"]))
            first = False
        for spk, line in v.get("dialogue", []):
            pb_rows.append((n if first else "", RESKIN_NAME[n] if first else "", "dialogue", spk, line))
            first = False
sheet("Post-Battle",
      ["#", "Chapter (re-skin)", "Kind", "Speaker", "Text"],
      pb_rows, [5, 20, 10, 18, 100], bold_cols=(2, 4))

ws_banter = sheet("Banter",
                  ["#", "Chapter (re-skin)", "Original Speaker", "Original Line", "Re-skin Speaker", "Re-skin Line"],
                  banter_rows, [5, 20, 16, 50, 18, 64], bold_cols=(2, 5))

# ---- highlight (amber) the cells that warrant the user's review ----
review = 0
for row in ws_char.iter_rows(min_row=2):          # heroes with no game unit yet
    if (row[0].value or "") == "(new recruit)":
        row[0].fill = REVIEW
        review += 1
for row in ws_banter.iter_rows(min_row=2):        # the two Ch.42 ending lines
    if str(row[5].value or "").startswith("Ending"):
        row[5].fill = REVIEW
        review += 1

wb.save(OUT)
print(f"highlighted {review} cells for review")
print("wrote", OUT)
