#!/usr/bin/env python3
"""Pull canonical per-chapter narration from the Terra Battle wiki /Story pages
and write text/autogenerated/script_<slug>.json for each chapter.

Each wiki "<Page>/Story" holds a <poem> block split into beats by '----'. We
clean the wikitext, split into panels, and emit the script-cutscene format
[{"line": ...}]. These JSON files are read at runtime (FileAccess), so no Godot
import is needed. Ch1-3 keep their hand-written narration unless --all is passed.

Run: python3 tools/fetch_story.py
"""
import json
import os
import re
import sys
import urllib.parse
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATASET = os.path.join(ROOT, "tools", "out", "terra_dataset.json")
OUTDIR = os.path.join(ROOT, "text", "autogenerated")
API = "https://terrabattle.fandom.com/api.php"
UA = "TerraBattleFanRecreation-StoryBot/1.0 (personal research)"
KEEP = {"borderlands", "to_the_capital", "melting_pot"}   # hand-written already


def title_key(name):
    return re.sub(r"[^A-Z0-9]+", "_", name.upper()).strip("_")


def api_get(params):
    url = API + "?" + urllib.parse.urlencode(dict(params, format="json", formatversion="2"))
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.load(r)


def fetch_batch(titles):
    d = api_get({"action": "query", "prop": "revisions", "rvprop": "content",
                 "rvslots": "main", "redirects": "1", "titles": "|".join(titles)})
    q = d["query"]
    resolve = {}
    for n in q.get("normalized", []) + q.get("redirects", []):
        resolve[n["from"]] = n["to"]
    content = {}
    for p in q.get("pages", []):
        content[p["title"]] = p["revisions"][0]["slots"]["main"]["content"] if p.get("revisions") else None

    def final(t):
        seen = set()
        while t in resolve and t not in seen:
            seen.add(t)
            t = resolve[t]
        return t
    return content, final


def clean(text):
    text = re.sub(r"\{\{[^}]*\}\}", "", text)              # templates
    text = re.sub(r"\[\[[^\]|]*\|([^\]]*)\]\]", r"\1", text)  # [[a|b]] -> b
    text = re.sub(r"\[\[([^\]]*)\]\]", r"\1", text)        # [[a]] -> a
    text = re.sub(r"'''?", "", text)                       # bold/italic markers
    text = text.replace("<br>", "\n").replace("<br/>", "\n").replace("<br />", "\n")
    text = re.sub(r"<[^>]+>", "", text)                    # stray tags
    return text


def parse_story(wikitext):
    m = re.search(r"<poem>(.*?)</poem>", wikitext, re.S)
    body = m.group(1) if m else wikitext
    body = re.sub(r"^\s*==.*==\s*$", "", body, flags=re.M)  # drop the chapter header
    panels = []
    for section in re.split(r"^\s*-{3,}\s*$", body, flags=re.M):
        s = clean(section)
        lines = [ln.rstrip() for ln in s.splitlines()]
        s = "\n".join(lines).strip("\n ")
        s = re.sub(r"\n{3,}", "\n\n", s)
        if len(s) >= 3:
            panels.append({"line": s})
    return panels[:8]


def main():
    do_all = "--all" in sys.argv
    data = json.load(open(DATASET))
    chapters = [(c["num"], title_key(c["name"]).lower(), c["page"]) for c in data["chapters"]]
    titles = [pg + "/Story" for _, _, pg in chapters]
    content, final = fetch_batch(titles)

    wrote, missing, skipped = 0, [], 0
    for num, slug, pg in chapters:
        if slug in KEEP and not do_all:
            skipped += 1
            continue
        wt = content.get(final(pg + "/Story"))
        if not wt:
            missing.append(num)
            continue
        panels = parse_story(wt)
        if not panels:
            missing.append(num)
            continue
        json.dump(panels, open(os.path.join(OUTDIR, f"script_{slug}.json"), "w"), indent=1, ensure_ascii=False)
        wrote += 1
    print(f"wrote {wrote} story files, kept {skipped} hand-written, missing {missing}")


if __name__ == "__main__":
    main()
