#!/usr/bin/env python3
# Appends the "Job 2 and Job 3 portraits" section to docs/placeholder_art.md,
# listing every job subjob art file so an artist / AI generator can replace them.
# Idempotent: does nothing if the section already exists. Reads /tmp/heroes.json.
#   python3 tools/gen_jobs_manifest.py
import os
import json

ROOT = os.path.join(os.path.dirname(__file__), "..")
MANIFEST = os.path.join(ROOT, "docs", "placeholder_art.md")
HEROES = json.load(open("/tmp/heroes.json"))

MARKER = "## Job 2 and Job 3 portraits (Jobs system)"

JOBS = [
    ("job2", "Job 2 (Vanguard)", "an armored, heavier melee build in a steel-blue palette (plating, a shield or heavy weapon, a grounded stance)"),
    ("job3", "Job 3 (Adept)", "a spellcasting build in a violet palette (robes or wraps, a staff or arcane focus, magical light)"),
]

INTRO = """
%s
Each hero has up to three jobs (Terra Battle classes), each with its own stats, skills, and artwork. Job 1 is the recruited form (its existing base art). Job 2 and Job 3 currently ship as PLACEHOLDER art: the base portrait tinted (Job 2 steel-blue, Job 3 violet) by `tools/gen_subjob_art.py`. Real art should show the **same character re-classed**. Match the game's painterly character-art style, keep the same dimensions and transparent background, overwrite the file at *Path*, then re-run `godot --headless --import`.

### Placeholder stats and skills (regenerate with real design later)
Stats and skill sets are generated by `tools/gen_subjobs.gd` and inlined into each job `.tres` under `jobs/terra/subjobs/`. To author real jobs, edit those `.tres` or re-run the generator with new numbers. Current placeholders, relative to the hero's base stats:

| Job | Role | HP | ATK | DEF | S.ATK | S.DEF | Weapon | Skills (placeholder) |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
| Job 2 | Vanguard | x1.4 | x1.15 | x1.4 | x1.0 | x1.25 | base | Slash, Counterattack |
| Job 3 | Adept | x1.2 | x0.9 | x1.1 | x1.7 | x1.4 | Staff | Fire, Ice, Heal |

### Art files
| Hero | Job | Kind | Path | Description |
| --- | --- | --- | --- | --- |
""" % MARKER


def main():
    text = open(MANIFEST).read()

    if MARKER in text:
        print("jobs section already present; nothing to do")
        return

    rows = []
    for h in HEROES:
        name = h["name"]
        slug = h["slug"]
        for key, label, blurb in JOBS:
            rows.append("| %s | %s | full | `assets/terra/subjobs/%s_%s_full.png` | %s re-classed as %s. |" % (
                name, label, slug, key, name, blurb))
            rows.append("| %s | %s | token | `assets/terra/subjobs/%s_%s_token.png` | Thumbnail of the above. |" % (
                name, label, slug, key))

    with open(MANIFEST, "a") as f:
        f.write(INTRO)
        f.write("\n".join(rows))
        f.write("\n")

    print("appended jobs section: %d heroes, %d art rows" % (len(HEROES), len(rows)))


main()
