#!/usr/bin/env python3
"""Wire the Water Margin re-skin TEXT into the game (story layer).

Single source of truth = tools/build_reskin_xlsx.py (the data the user reviewed).
Importing it rebuilds the xlsx as a harmless side effect, and exposes:
  RESKIN_NAME[n]   -> re-skin chapter name
  RESKIN_NARR[n]   -> re-skin opening narration (one paragraph)
  RESKIN_BANTER[n] -> [(SPEAKER, line), ...]
  CHARACTERS       -> rows whose [1] is the proper-case re-skin name

Writes:
  text/autogenerated/script_<slug>.json   (narration, split into ~2-sentence pages)
  text/autogenerated/dialogue_<slug>.json  (banter, proper-case speakers)
  text/autogenerated/script_<slug>_post_battle.json   (aftermath beats, optional)
  text/autogenerated/dialogue_<slug>_post_battle.json (aftermath banter, optional)
  text/text.csv                            (chapter title + caption -> re-skin)

Post-battle sources live in tools/reskin_post_battle.json ({num: {script, dialogue}});
chapters without an entry get their stale post-battle files removed (re-runnable).
The engine plays them via ui/cutscenes/post_battle_script_cutscene.tscn (victory ->
post-battle script -> post-battle dialogue -> pre-battle menu; missing files skip).

This is a text/name overlay only; no battle or stage data changes. Re-runnable.
Run: python3 tools/wire_reskin_into_game.py
Then: godot --headless --import   (recompiles text.csv -> .translation)
"""
import csv
import json
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import build_reskin_xlsx as R  # noqa: E402  (side effect: rebuilds the xlsx)

ROOT = R.ROOT
AUTOGEN = os.path.join(ROOT, "text", "autogenerated")
CSV = os.path.join(ROOT, "text", "text.csv")


def clean(t):
    return (t or "").replace(" — ", " - ").replace("—", "-").replace("–", "-")


# Proper-case speaker map from the character roster; fall back to title-case.
SPK = {c[1].upper(): c[1] for c in R.CHARACTERS}


def speaker(name):
    return SPK.get(name, name.title())


def narr_pages(text):
    sents = re.split(r"(?<=[.!?]) +", clean(text).strip())
    sents = [s for s in sents if s]
    pages = [" ".join(sents[i:i + 2]) for i in range(0, len(sents), 2)]
    return [{"line": p} for p in (pages or [clean(text)])]


def caption_from(text):
    s = re.split(r"(?<=[.!?]) +", clean(text).strip())[0]
    if len(s) > 100:
        s = s[:97].rsplit(" ", 1)[0].rstrip(" ,;:-") + "..."
    return s


def ordered_chapters():
    """[(num, slug, title_key)] in story order."""
    lst = open(os.path.join(ROOT, "chapter_data", "main_story_chapter_list.tres")).read()
    slugs = re.findall(r"chapter_data/terra/([a-z0-9_]+)\.tres", lst)
    out = []
    for i, slug in enumerate(slugs, 1):
        txt = open(os.path.join(ROOT, "chapter_data", "terra", slug + ".tres")).read()
        title = re.search(r'title = "([^"]+)"', txt).group(1)
        out.append((i, slug, title))
    return out


def main():
    chapters = ordered_chapters()
    assert len(chapters) == 42, "expected 42 chapters, got %d" % len(chapters)

    pb_path = os.path.join(ROOT, "tools", "reskin_post_battle.json")
    post_battle = {}
    if os.path.exists(pb_path):
        post_battle = {int(k): v for k, v in json.load(open(pb_path)).items()}

    name_updates = {}   # csv key -> reskin text (en==es)
    n_narr = n_banter = n_pb_script = n_pb_banter = 0

    for num, slug, title_key in chapters:
        # narration
        pages = narr_pages(R.RESKIN_NARR[num])
        with open(os.path.join(AUTOGEN, "script_%s.json" % slug), "w") as f:
            json.dump(pages, f, indent=1, ensure_ascii=False)
        n_narr += 1

        # banter (only where the re-skin provides it)
        banter = R.RESKIN_BANTER.get(num, [])
        if banter:
            rows = [{"speaker": speaker(spk), "line": clean(line)} for spk, line in banter]
            with open(os.path.join(AUTOGEN, "dialogue_%s.json" % slug), "w") as f:
                json.dump(rows, f, indent=1, ensure_ascii=False)
            n_banter += 1

        # post-battle aftermath (script and/or dialogue; remove stale files otherwise)
        pb = post_battle.get(num, {})
        pb_script_path = os.path.join(AUTOGEN, "script_%s_post_battle.json" % slug)
        pb_dialogue_path = os.path.join(AUTOGEN, "dialogue_%s_post_battle.json" % slug)

        if pb.get("script"):
            with open(pb_script_path, "w") as f:
                json.dump(narr_pages(pb["script"]), f, indent=1, ensure_ascii=False)
            n_pb_script += 1
        elif os.path.exists(pb_script_path):
            os.remove(pb_script_path)

        if pb.get("dialogue"):
            rows = [{"speaker": speaker(spk), "line": clean(line)} for spk, line in pb["dialogue"]]
            with open(pb_dialogue_path, "w") as f:
                json.dump(rows, f, indent=1, ensure_ascii=False)
            n_pb_banter += 1
        elif os.path.exists(pb_dialogue_path):
            os.remove(pb_dialogue_path)

        # chapter name + caption -> text.csv
        name_updates[title_key] = clean(R.RESKIN_NAME[num])
        name_updates[title_key + "_CAPTION"] = caption_from(R.RESKIN_NARR[num])

    # rewrite text.csv, overriding en+es for the chapter keys
    rows = list(csv.reader(open(CSV, encoding="utf-8")))
    changed = 0
    for r in rows:
        if r and r[0] in name_updates:
            val = name_updates[r[0]]
            if len(r) >= 3:
                r[1], r[2] = val, val
                changed += 1
    with open(CSV, "w", encoding="utf-8", newline="") as f:
        csv.writer(f).writerows(rows)

    print("narration files: %d, banter files: %d" % (n_narr, n_banter))
    print("post-battle scripts: %d, post-battle banters: %d" % (n_pb_script, n_pb_banter))
    print("text.csv keys updated: %d (of %d targeted)" % (changed, len(name_updates)))


if __name__ == "__main__":
    main()
