class_name ButtonIcons
# Applies the shared gold glyph set (assets/ui/icons/<name>.png, generated by
# tools/gen_button_icons.py) to a Button. Every button in the game receives
# its icon through this helper so size and spacing stay uniform.

const _DIR := "res://assets/ui/icons/"
const _MAX_WIDTH := 22
const _MAX_WIDTH_GLYPH_ONLY := 24


static func apply(button: Button, icon_name: String) -> void:
	var path := _DIR + icon_name + ".png"

	if not ResourceLoader.exists(path):
		push_warning("ButtonIcons: missing icon %s" % path)
		return

	button.icon = load(path)
	# Left gutter: Godot positions icon and text independently, so centering
	# both overlaps them. The glyph sits at the left content edge and the
	# label keeps its own alignment.
	button.expand_icon = false
	button.icon_alignment = HORIZONTAL_ALIGNMENT_LEFT
	button.add_theme_constant_override("icon_max_width", _MAX_WIDTH)
	button.add_theme_constant_override("h_separation", 7)


# For compact controls that are pure glyphs (pause, fast forward): the icon
# replaces the text entirely and sits centered.
static func apply_icon_only(button: Button, icon_name: String) -> void:
	apply(button, icon_name)

	if button.icon != null:
		button.text = ""
		button.icon_alignment = HORIZONTAL_ALIGNMENT_CENTER
		button.add_theme_constant_override("icon_max_width", _MAX_WIDTH_GLYPH_ONLY)
